### ISSUE TITLE
Could not connect to a default or fallback server

### ISSUE THREAD

**Issue by ventoryprod** [Kamesuta/BungeePteroPower#9]
When joining to Bungee server that redirects to the actual server without any lobby between them, causes the next error on connection: Could not connect to a default or fallback server. Incorrectly configured address/port/firewall?

I assume that it's limitation of the bungeecord, but if it is not, is there a possibility to make it work when no lobby server with portals to join the server is used, and if yes, then how because seems like I messed up somewhere.

**Comment by Kamesuta** [comment]
Thanks for your request!

It is true that if you set the lobby itself to start up with BungeePteroPower, the message on kick will show the Bungeecord error message.    
I would like to have the kick message tell you that the server is starting up when you log in, but it seems to be a bit difficult due to Bungeecord limitations.  

I am unable to respond immediately, but will investigate when I have time!

**Comment by ventoryprod** [comment]
Cool, I will make a lobby server until it will (if it ever will) be possible to startup server without triggering that in the lobby

**Comment by Kamesuta** [comment]
Happy to announce that I have implemented a feature in [v1.7](https://github.com/Kamesuta/BungeePteroPower/releases/tag/v1.7) that you have been asking for!  
You can now see a custom message when logging in if the lobby server is down.  
![2024-03-10_01h41_43](https://github.com/Kamesuta/BungeePteroPower/assets/16362824/6eccad87-eaa7-4577-905d-f5016ea3d5c6)

However, this feature is disabled by default.  
To enable it, please turn on `useSynchronousPing` in config.yml.  

Due to the limitations of Bungeecord, during a ServerConnectEvent this feature blocks the thread until the ping is completed.  
After the ping completes, let the thread continue and disconnect the player with a message if the lobby server is not open.

**Comment by TufftyMirror3585** [comment]
is there something other than useSynchronousPing that needs to be on as the name on the plugin and on bungeecord is the same and i still get the default message even though if i run the start command it works is there a bungeecord setting that interferes with it as i have tried turning off ping passthrough

**Comment by Kamesuta** [comment]
Currently BungeeCord does not support to remove default message via plugin, so this is not possible.  
I have submitted a pull request to BungeeCord to add an event for login failures, so that the default message can be removed once it is merged.

▼ Pull request to BungeeCord  
https://github.com/SpigotMC/BungeeCord/pull/3638

▼ If the pull request is merged, the following modifications can be made to improve the situation.  
https://github.com/Kamesuta/BungeePteroPower/pull/11
